pipeline {
    agent any
    stages {
        stage("Liora Env Variables") {
            steps {
                echo "The build id is ${env.BUILD_ID} or $BUILD_ID or ${BUILD_ID}"
            }
        }
    }
}
